### PR TITLE
Improve some documentation

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by Gabriel439** [comment]
Thanks!  I only have one request, which is to explicitly use `Groups a m x -> Groups a m x` instead of `Transformation a m x`, but other than that this looks good.

**Comment by mitchellwrosen** [comment]
Sure, done

**Comment by Gabriel439** [comment]
Oops!  I just realized that you also had `Splitter` and `Joiner`.  In that case go back to the way that you had before and add back `Transformation` for consistency.  Sorry about that! :)

**Comment by mitchellwrosen** [comment]
The deed is done.

**Comment by Gabriel439** [comment]
Thank you!  Sorry about all the trouble :)

**Pull request merged**
